name: Check Latest Ban List

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
    - run: npm install
    - run: node index.js
    - name: push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Lists updated'
        commit_user_name: '🤖 SV ban checker bot'
        commit_author: gh-actions <actions@github.com>
